name: Base Workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:

jobs:

  build-and-test:
  
      runs-on: ubuntu-latest
  
      steps:

      - name: Debug file structure
        run: |
          pwd
          ls -la
          
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          docker-compose up -d --build
          chmod +x app/entrypoint.sh
          ./app/entrypoint.sh
          docker-compose exec -T movies ruff check . --exclude=env
          docker-compose exec -T movies pytest
          